### ISSUE TITLE
setting for auto or not auto enter focus mode.

### ISSUE THREAD

**Issue by Connor-yang96** [ryanpcmcquen/obsidian-focus-mode#1]
setting for auto or not auto enter focus mode.

**Comment by ryanpcmcquen** [comment]
I have a strong bias toward 'no settings'. So there would need to be a lot of demand to offer this.

Conversely, we could create a forked plugin once this is established as stable and have that behavior be the default of the other plugin.

**Comment by Connor-yang96** [comment]
without settings, but need click icon for enter focus mode. 

or without setting, no need click icon enter focus mode.

**Comment by ryanpcmcquen** [comment]
So does focus mode disappear when you stop typing in the 'while typing' design? That seems distracting.

**Comment by Connor-yang96** [comment]
no stop while stoping typing, when move mouse, leave focus mode.

**Comment by ryanpcmcquen** [comment]
This sounds gross design/engineering wise.

**Comment by ryanpcmcquen** [comment]
The hope is that you lock into focus mode for a prolonged period (to get some focused writing done).

The interaction of one mouse click before 15-30 minutes of focused work seems very small, and it also keeps this plugin simple and performant.
