### ISSUE TITLE
Bug in correlation with ObsidianTabs Plugin

### ISSUE THREAD

**Issue by tim-hilde** [ryanpcmcquen/obsidian-focus-mode#12]
Using version 1.4.1 in contrast to 1.4.0 leads to a bug in the tab bar. The video shows it quite nicely.

https://user-images.githubusercontent.com/44113468/119495915-398ebd80-bd63-11eb-8e8b-99fa5f95d440.mov

**Comment by ryanpcmcquen** [comment]
Darn, the 1.4.1 changes fixed the issues with the California Coast theme. Maybe @AidenLx has some ideas here as well.

**Comment by AidenLx** [comment]
This may not be an theme issue. What plugin are you using for tab bar?

**Comment by tim-hilde** [comment]
I'm using the [Obsidian Tabs plugin ](https://github.com/gitobsidiantutorial/obsidian-tabs)

**Comment by ryanpcmcquen** [comment]
@tim-hilde have you created an issue against that plugin for this? I think they are doing some weird parsing if our CSS changes are breaking things ...

**Comment by tim-hilde** [comment]
Not yet, as the bug came up only after your 1.4.1 version

**Comment by shaggyfeng** [comment]
I love Focus Mode. But this is happening in all the Topaz themes as well, when multiple tabs are opened.

**Comment by ryanpcmcquen** [comment]
The weird thing is that we really only adjust CSS with this plugin. So I'm not sure what the tabs plugin is parsing to produce this ...

**Comment by AidenLx** [comment]
It seems that the plugin in changing the style of workleaf itself into tab…will have to look into this

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ryan McQuen ***@***.***>
发送时间: Thursday, May 27, 2021 7:48:02 AM
收件人: ryanpcmcquen/obsidian-focus-mode ***@***.***>
抄送: AidenLx ***@***.***>; Mention ***@***.***>
主题: Re: [ryanpcmcquen/obsidian-focus-mode] Bug in correlation with ObsidianTabs Plugin (#12)


The weird thing is that we really only adjust CSS with this plugin. So I'm not sure what the tabs plugin is parsing to produce this ...

―

**Comment by ryanpcmcquen** [comment]
Can everyone try 1.5.0?

**Comment by AidenLx** [comment]
I've tried, not the problem of app container. It still behave as before.

**Comment by shaggyfeng** [comment]
It is still happening in 1.5.0

> Can everyone try 1.5.0?

**Comment by ryanpcmcquen** [comment]
> It is still happening in 1.5.0
> 
> > Can everyone try 1.5.0?

Thanks for checking it out. Does 1.4.0 still work as expected? Does it affect 'Focus Mode' and 'Super Focus Mode'?

**Comment by shaggyfeng** [comment]
> > It is still happening in 1.5.0
> > > Can everyone try 1.5.0?
> 
> Thanks for checking it out. Does 1.4.0 still work as expected? Does it affect 'Focus Mode' and 'Super Focus Mode'?

1.4.0 works without the issue.

**Comment by AidenLx** [comment]
> > > It is still happening in 1.5.0
> 
> > > > Can everyone try 1.5.0?
> 
> > 
> 
> > Thanks for checking it out. Does 1.4.0 still work as expected? Does it affect 'Focus Mode' and 'Super Focus Mode'?
> 
> 
> 
> 1.4.0 works without the issue.

How does it look like when in 1.4.0?

**Comment by ryanpcmcquen** [comment]
> 
> 
> > > It is still happening in 1.5.0
> > > > Can everyone try 1.5.0?
> > 
> > 
> > Thanks for checking it out. Does 1.4.0 still work as expected? Does it affect 'Focus Mode' and 'Super Focus Mode'?
> 
> 1.4.0 works without the issue.

Is the issue present in Normal and Super modes?

**Comment by shaggyfeng** [comment]
> > > > It is still happening in 1.5.0
> > > > > Can everyone try 1.5.0?
> > > 
> > > 
> > > Thanks for checking it out. Does 1.4.0 still work as expected? Does it affect 'Focus Mode' and 'Super Focus Mode'?
> > 
> > 
> > 1.4.0 works without the issue.
> 
> Is the issue present in Normal and Super modes?
![1 4 0-focus mode](https://user-images.githubusercontent.com/75353922/119765865-faa35980-be81-11eb-996b-60b4b2c8b14a.png)
1 4 0-focus mode
***
![1 4 0-super fm](https://user-images.githubusercontent.com/75353922/119765899-0a22a280-be82-11eb-9608-b214306f6a86.png)
1 4 0-super fm
***
![1 5 0-focus mode](https://user-images.githubusercontent.com/75353922/119765918-14dd3780-be82-11eb-9322-2d0f5d573176.png)
1 5 0-focus mode (has issue)
***
![1 5 0-super fm](https://user-images.githubusercontent.com/75353922/119765944-232b5380-be82-11eb-840e-478febd71d31.png)
1 5 0-super fm

**Comment by ryanpcmcquen** [comment]
So the issue is _only_ present in normal mode. That should help debugging, thanks for checking!

**Comment by AidenLx** [comment]
![image](https://user-images.githubusercontent.com/31102694/119768815-e300bb00-beeb-11eb-955a-84cb5f87587f.png)

It's fixed here, for anyone who need to patch themselves, here are the css snippet: 
```css
.focus-mode.plugin-tabs .stayopen div.view-header {
  display: none;
}
.focus-mode.plugin-tabs div.view-header {
  display: flex;
}
.focus-mode.plugin-tabs div.view-actions {
  display: none;
}
```

**Comment by ryanpcmcquen** [comment]
The fix will land in 1.6.0 tomorrow. Thank you @AidenLx!

**Comment by ryanpcmcquen** [comment]
Upstream beat me to a fix, but then they reverted. So I re-reverted the revert? Unreverted? I have no idea what I am saying, but 1.6.0 is out now with @AidenLx's awesome fix!

**Comment by tim-hilde** [comment]
Sad to say it, but the bug is back again in 0.12.5...

**Comment by ryanpcmcquen** [comment]
I think the Tabs plugin may need to implement their fix too.
