### ISSUE TITLE
Focus mode affecting left ribbon on Red Graphite theme

### ISSUE THREAD

**Issue by oldjove** [ryanpcmcquen/obsidian-focus-mode#14]
Hi, I'm getting an issue when starting up Obsidian with Focus Mode enabled. When I open Obsidian, the left ribbon is entirely white and the only icon visible is Focus Mode. Toggling Focus Mode returns the view to normal. Disabling Focus Mode removes the issue.

Using the Red Graphite theme.

**Comment by ryanpcmcquen** [comment]
That's a weird one. I won't have time to dig into this for a while, but maybe someone else can resolve it. Does it happen with all versions of Focus Mode, or did it start happening recently?

**Comment by ryanpcmcquen** [comment]
I've installed Red Graphite here and I cannot reproduce the issue on `1.6.0`. What other plugins do you have?

**Comment by oldjove** [comment]
This has just started happening. It began on my work PC today after I updated my plugins. I'm at home now on my laptop. I didn't have focus mode installed here and Obsidian was working as normal. I installed focus mode (1.6.0) and now it's happening here too. 

I've also tested this using the default theme and the behaviour is the same -- so it doesn't look like it's theme-related.

As for my plugins, I have a lot. I'm not sure if there's a better way to list them all, but here's a screenshot of the contents of my plugins folder on the laptop:

![image](https://user-images.githubusercontent.com/47560940/119878045-00547a00-bf2a-11eb-9807-74a312dff9b9.png)

**Comment by ryanpcmcquen** [comment]
> This has just started happening. It began on my work PC today after I updated my plugins. I'm at home now on my laptop. I didn't have focus mode installed here and Obsidian was working as normal. I installed focus mode (1.6.0) and now it's happening here too.
> 
> I've also tested this using the default theme and the behaviour is the same -- so it doesn't look like it's theme-related.
> 
> As for my plugins, I have a lot. I'm not sure if there's a better way to list them all, but here's a screenshot of the contents of my plugins folder on the laptop:
> 
> ![image](https://user-images.githubusercontent.com/47560940/119878045-00547a00-bf2a-11eb-9807-74a312dff9b9.png)

Can you repro it with no other plugins? Maybe try the 'Help vault'?

**Comment by oldjove** [comment]
Hmm, well I disabled all my plugins except focus mode and that solved the problem. I've now reenabled them all and everything is working fine. Maybe something to do with the order that the plugins were being loaded? Anyway, I suppose you can close this. Seems like it might not be a general problem.

**Comment by ryanpcmcquen** [comment]
That is interesting. I don't know of a way to change plugin order without some nasty hack like `setTimeout`. If it happens again, I would say do a binary search comparison of plugins (split plugins into two equal groups and try to repro the bug with either group, subdividing at each repro until you find the offender).

**Comment by oldjove** [comment]
We have a winner. I disabled my plugins on my work computer one by one. It appears that Minimal Theme Settings was causing the bug. Strange, cos I'm not using Minimal Theme at present. I've uninstalled MTS and I'm happy again. ;-)

**Comment by ryanpcmcquen** [comment]
> We have a winner. I disabled my plugins on my work computer one by one. It appears that Minimal Theme Settings was causing the bug. Strange, cos I'm not using Minimal Theme at present. I've uninstalled MTS and I'm happy again. ;-)

Perhaps there is a bug with that plugin when minimal theme is not enabled.
