### ISSUE TITLE
Make opacity of other paragraphs an option

### ISSUE THREAD

**Issue by apotenza92** [ryanpcmcquen/obsidian-focus-mode#17]
Hi, love this plugin, but one thing I've had to do manually is go into the CSS style and remove the opacity option that dims out other paragraphs when focus mode is activated. I find it quite distracting and unnecessary.

Is there a possibility to make this a user-facing option within Obsidian's settings menu?

Just a suggestion. Thanks!

**Comment by ryanpcmcquen** [comment]
It is certainly possible, but I find settings/options very distracting. It is easy enough to adjust with custom CSS, I would rather just have a sensible default.

That being said, I am not crazy about the opacity and have increased it a few times. Would bumping it to `0.85` or `0.9` be a happy compromise?

**Comment by ryanpcmcquen** [comment]
I bumped it to `0.85`. `0.9` was too subtle to even notice, and I kind of missed it.

**Comment by rsomani95** [comment]
@ryanpcmcquen FWIW, I'd love to have this as an option as well. I don't mind writing the custom CSS, but I can envision scenarios where having it as an option would be more favorable than changing custom CSS.

For instance, there are times when I toggle focus mode just to get rid of everything else and use it as my "normal" mode. I'd ideally want the opacity turned off here, and then in _super focus_ mode, it'd be nice to have it turned on. This may also change based on the kind of writing one is doing. If it's a shorter note, you may not want the opacity on, but for longer form writing, you might. Changing the CSS becomes clunky, and adds too much context switching overhead. Having an option would be really nice!


---

PS: Thank you for your work on this. This is one of my favorite and most used plugins :)

**Comment by ryanpcmcquen** [comment]
@rsomani95, that would be even more complex, since you'd need options like:

- No opacity modification
- No opacity modification in focus mode
- Always have opacity modification

I just don't see the value enough to increase the complexity of the plugin. I would consider adding a special class to Super Focus Mode so that a user could implement the above request with custom CSS.

>Changing the CSS becomes clunky, and adds too much context switching overhead.

Could you expand on this a bit? If we separated Super and Normal modes by class, would that make it less clunky, or is there something else that makes this clunky?

**Comment by ryanpcmcquen** [comment]
Seems to me you could just add snippets for whatever kind of state you want if we had an extra `.super-focus-mode` class:
<img width="1412" alt="Screen Shot 2021-06-21 at 8 53 34 PM" src="https://user-images.githubusercontent.com/772937/122860565-ced59100-d2d2-11eb-84fd-d0719dc99381.png">

**Comment by rsomani95** [comment]
@ryanpcmcquen `.super-focus-mode` would totally solve this problem.

**Comment by ryanpcmcquen** [comment]
@rsomani95 @apotenza92:
https://github.com/ryanpcmcquen/obsidian-focus-mode/releases/tag/1.8.0
