### ISSUE TITLE
Adding a setting to switch focus mode and super focus mode

### ISSUE THREAD

**Issue by jgsource** [ryanpcmcquen/obsidian-focus-mode#18]
I usually use 2 panes but prefer to focus on the active pane. It would be great if you could add a setting to switch the 2 modes so I can just click on the button to activate super focus mode, and use shift + click on the button to activate focus mode instead.

**Comment by ryanpcmcquen** [comment]
Sorry, but I don't feel this is worth adding the complexity of having settings.
