### ISSUE TITLE
Bug? Note title isn't hidden on single/first pane

### ISSUE THREAD

**Issue by frankreporting** [ryanpcmcquen/obsidian-focus-mode#19]
I'm getting a behavior that is different from the screenshots/gifs in the readme file. In your demo, all note titles are hidden in focus mode. In my case, if I have only one pane open, it stays visible in focus mode, although the note controls disappear. If I have more than one pane, the title is only hidden on _additional_ panes, and not on the first/leftmost one. In your demo, ALL note titles are hidden.

I'm on macOS Big Sur, Obsidian 0.12.13 insider edition.

I'm not sure if I have another plugin conflicting or if this is an OS specific thing, or if other users are seeing the same limitation. I'll report back if I can isolate a plugin conflict.

**Comment by ryanpcmcquen** [comment]
Can you try with all other plugins disabled?

**Comment by frankreporting** [comment]
Got it.. it's the Hider plugin, specifically the setting "Hide title bar (frameless mode)." With that setting enabled, the title bar disappears, and the note title appears at the very top where the title bar would have been. What's strange is the div classes appear to be the same either way:  .view-header >  .view-header-title-container > .workspace-leaf.mod-active .view-header-title. And in frameless mode, the controls (edit/close/ellipsis menu) are hidden in focus mode. It's just the title that's not being hidden.

**Comment by ryanpcmcquen** [comment]
My guess would be a changed DOM structure, _or_ the 'Hider' plugin is using an `!important` rule.

**Comment by frankreporting** [comment]
Understood.. I don't see anything like that in the [stylesheet on the Hider repo](https://github.com/kepano/obsidian-hider/blob/master/styles.css), and it doesn't look like the author made it possible to track issues. But I can try to play around to see if I can figure it out, too.

**Comment by ryanpcmcquen** [comment]
Yeah, they add classes to the document body, which gives the Hider CSS rules 'priority' (because of increased specificity).

Not sure there is a good way to fix this on my end without an ugly hack.

**Comment by frankreporting** [comment]
It looks like the .view-actions DOM element is unchanged when Hider goes into frameless mode. However, Hider adds the ::before element to the .view-header-title div. I'll ask the dev, kepano, if that's something that might be changed in Hider.
```
<div class="view-header-title" contenteditable="true" spellcheck="false" tabindex="-1">
   ::before
   2021-08-10
</div>
```

**Comment by frankreporting** [comment]
Hey just letting you know I found the issue, and it was in the Minimal Theme CSS. Not sure if you'd want to try implementing this in Focus Mode, but I also told the Minimal Theme dev about the possible fix. And for anyone else who's also nitpicky like me and wanted to have Minimal Theme AND be able to hide the title, here's the CSS that did the trick (I added it directly to the Minimal Theme stylesheet in the theme folder, so it will break on update.. this is not a permanent fix):

```
/* Hide Title area when hiding View actions in Minimal Theme Settings  */ 

.view-header-title-container {
  transition:opacity 0.25s ease-in-out;
}

.view-header-title-container.is-active {
  opacity:1;
}

.workspace-ribbon:not(.is-collapsed) ~ .mod-root .view-header-title-container,
.focus-mode .workspace-ribbon:not(.is-collapsed) ~ .mod-root .view-header:hover .view-header-title-container,
.workspace-ribbon.mod-left.is-collapsed ~ .mod-root .view-header:hover .view-header-title-container,
.mod-right.is-collapsed ~ .mod-root .view-header:hover .view-header-title-container {
  opacity:1;
  transition:opacity 0.25s ease-in-out;
}

.focus-mode .view-header-title-container,
.focus-mode .workspace-ribbon.mod-right.is-collapsed ~ .mod-root .view-header-title-container,
.focus-mode .workspace-ribbon.mod-left.is-collapsed ~ .mod-root .view-header-title-container {
  opacity:0;
  transition:opacity 0.25s ease-in-out;
}
```
