### ISSUE TITLE
Keyboard shortcut for activating focus mode

### ISSUE THREAD

**Issue by HazemKaroui** [ryanpcmcquen/obsidian-focus-mode#2]
Would be very helpful if there was a configurable hotkey for toggling focus mode.
Thank you for the plugin by the way I've been wishing for a de-cluttered view in obsidian.

**Comment by ryanpcmcquen** [comment]
That has conflicts on Mac OS.

**Comment by ryanpcmcquen** [comment]
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>F</kbd> may be a suitable cross platform default.

**Comment by ryanpcmcquen** [comment]
This isn't high priority to me, so I added a 'help wanted' label if someone wants to tackle this.

**Comment by AidenLx** [comment]
> Ctrl + Alt + F may be a suitable cross platform default.

It conflicts with `find and replace in current note`, at least in macOS, I'm using `Ctrl + Alt + Shift + F` for now. 
![image](https://user-images.githubusercontent.com/31102694/119075916-396d8580-ba24-11eb-96bf-d83fb77f506b.png)

**Comment by ryanpcmcquen** [comment]
Let's choose a combination that will support the <kbd>Shift</kbd> modifier activating Super Focus. This brings consistency to the mouse and keyboard interactions.

**Comment by ryanpcmcquen** [comment]
Closed in: https://github.com/ryanpcmcquen/obsidian-focus-mode/releases/tag/1.4.0
