### ISSUE TITLE
Focus mode auto turned on when Obsidian is launched

### ISSUE THREAD

**Issue by steveeyre** [ryanpcmcquen/obsidian-focus-mode#20]
and, in this certain focus mode, the title of file will be hidden, which will show again after I swtiched Focus Mode off and on for once. Not quite sure is there a conflict between other plugins or snippets.

Thank you for this helpful plugin!

**Comment by ryanpcmcquen** [comment]
I cannot reproduce, have you tried without other plugins?

**Comment by steveeyre** [comment]
> I cannot reproduce, have you tried without other plugins?

Yes I'll try to make some tests, wish I could find the conflict since I installed too many plugins.

**Comment by ryanpcmcquen** [comment]
Have you tried reproducing with all other plugins disabled?

**Comment by ryanpcmcquen** [comment]
Haven't heard anything from you in a while, please reopen if you can find out what plugins are conflicting.
