### ISSUE TITLE
Focus mode with Timer 

### ISSUE THREAD

**Issue by skillhacker-code** [ryanpcmcquen/obsidian-focus-mode#21]
Can you please update the plugin with timer .

The goal is Focus mode with Timer

1. shouldn't be able to disable until the timer is finished.
2. shouldn't be disabled if obsidian is restarted.
3. Shouldn't be able to do anything that distracts.

Thank you so much

**Comment by ryanpcmcquen** [comment]
I'd rather not add that complexity to this plugin. You are welcome to fork it.
