### ISSUE TITLE
Problems writing in a note created while in focus mode

### ISSUE THREAD

**Issue by rasmusrhl** [ryanpcmcquen/obsidian-focus-mode#23]
### Problems with creating a new note while in focus mode
I can't write in a newly created note. To be able to write a newly created note, I have to click outside obsidian (e.g. the desktop) and then click on the note again. 

**Steps to reproduce:**

1. Open a note in obsidian.
2. Go to focus mode (ctrl + alt + z)
2. Create a new note (ctrl + n)
3. I can't write in the new note.
4. The ability to write in the note is reestablished by clicking on the desktop first, and then clicking back on the note. 

This happens with/without VIM-mode enabled.

**Comment by ryanpcmcquen** [comment]
Do you have any other plugins?

**Comment by rasmusrhl** [comment]
@ryanpcmcquen  
No. The problem persists even after disabling all other plugins (including core plugins), and restarting obsidian.

**Comment by ryanpcmcquen** [comment]
What version of the Obsidian installer do you have and what operating system?

**Comment by ryanpcmcquen** [comment]
Fixed in 1.8.1, let me know if you're still able to reproduce.

**Comment by rasmusrhl** [comment]
I can confirm: It's fixed in version 1.8.1! Thanks!

**Comment by ryanpcmcquen** [comment]
Thanks for reporting, that was a weird one.
