### ISSUE TITLE
Add fullscreen mode

### ISSUE THREAD

**Issue by 4m1n** [ryanpcmcquen/obsidian-focus-mode#24]
1\. Beside focus mode, add fullscreen mode in order to hide taskbar and title bar. Hiding the title bar is achievable through [Hider](https://github.com/kepano/obsidian-hider) but fullscreen mode's optionality offers a better UX.
2\. Add option to remove the plugin's toggle button in sidebar. We can use the keyboard shortcut instead.
3\. Add option to hide <kbd>Graph settings</kbd> and <kbd>Start timelapse animation</kbd> buttons in Graph View.

These will make the experience much cleaner. I would greatly appreciate it.

**Comment by ryanpcmcquen** [comment]
No thank you.
