### ISSUE TITLE
[Bug] When Obsidian launches, the focus mode is toggled from the start? 

### ISSUE THREAD

**Issue by seanjun21** [ryanpcmcquen/obsidian-focus-mode#25]
I think someone mentioned this earlier (one of the issues was similar), but when you launch Obsidian fresh, the focus mode is toggled. I'm not sure if it's ON or not because it's showing weird behavior (screenshot included)--basically hides all the side buttons except the focus button.

![image](https://user-images.githubusercontent.com/13973015/143710924-434d9f3b-be55-4f74-aa67-f87b89ea0cdf.png)

It gets kind of annoying because the intention of focus mode is to turn it on when I want to focus. And in order to get out of this mode, I have to toggle focus 2x (turn it ON and OFF) to see the full normal panel display. The current theme is minimal, but it's displaying the same error across all themes. 

![image](https://user-images.githubusercontent.com/13973015/143713503-2785e76b-f67a-4527-8869-493712c7cdf5.png)
![image](https://user-images.githubusercontent.com/13973015/143713767-ff23ba90-4711-468f-84c9-2634ab7a85d5.png)

This is the list of all plugins on my workspace.
Could you look this into?

**Comment by ryanpcmcquen** [comment]
Are you able to reproduce this with all other plugins disabled? The other issue was requesting it to be enabled on startup, so that's unrelated.

**Comment by seanjun21** [comment]
Ok, so I tracked all the plugins that I have installed. Basically tried your suggestion and tried enabling one-by-one to see which one is causing the issue.

Looks like it's the "Minimal Theme Setting" -- the plugin that comes with Minimal Theme.
The weird thing is ... it's showing the error when I'm not using the minimal theme. 

I hope that helped.

**Comment by ryanpcmcquen** [comment]
I imagine it is a bug with that plugin, and I don't use it.
