### ISSUE TITLE
Mobile support 

### ISSUE THREAD

**Issue by MisterY** [ryanpcmcquen/obsidian-focus-mode#26]
Hi!

Obsidian on Android states:

> This plugin does not support your device

How difficult would it be to make the plugin compatible?

**Comment by ryanpcmcquen** [comment]
It may already work on mobile, but since the UI is different I didn't think it would be useful. If I enable mobile support, would you be willing to provide feedback on how well it works?

**Comment by MisterY** [comment]
> It may already work on mobile, but since the UI is different I didn't think it would be useful. 

You are probably right. I was actually looking for what the Zoom plugin provides: "narrowing" in OrgMode vocabulary. Now I'm a bit confused about what exactly does this plugin do. I can't figure out from the demo videos, sorry! 

> If I enable mobile support, would you be willing to provide feedback on how well it works?

Absolutely! Especially since the Zoom plugin does not work on mobile.

**Comment by MisterY** [comment]
The mobile interface is already kinda focused.

**Comment by ryanpcmcquen** [comment]
It hides the UI except for the text and focus mode icon.

**Comment by ryanpcmcquen** [comment]
Yeah, I'm not sure this would be effective on mobile ...

**Comment by MisterY** [comment]
Yes, sorry! The mobile UI is already behaving that way, more or less.
