### ISSUE TITLE
Side bar shows only the Focus Mode icon after using keyboard shortcut once and twice

### ISSUE THREAD

**Issue by Hunanbean** [ryanpcmcquen/obsidian-focus-mode#27]
When using the keyboard shortcut ctrl+shift+alt+z it focuses on the selected pane properly (super focus mode). 
Pressing the shortcut again refocuses back to normal view, but the left sidebar only has the Focus Mode icon visible now.
To get all the icons back on the sidebar, i have to mouse click the Focus Mode icon.

Thank you

**Comment by ryanpcmcquen** [comment]
Or press <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Z</kbd>, this is expected behavior.
