### ISSUE TITLE
Using ctrl + alt + z to get out of super focus mode opens side bars that had been collapsed

### ISSUE THREAD

**Issue by Hunanbean** [ryanpcmcquen/obsidian-focus-mode#29]
Using ctrl + alt + z to get out of super focus mode opens die bars that had been collapsed

**Comment by ryanpcmcquen** [comment]
Yep, that's expected behavior.

**Comment by Hunanbean** [comment]
Perhaps you need to re-examine your design.

**Comment by ryanpcmcquen** [comment]
https://github.com/ryanpcmcquen/obsidian-focus-mode/issues/9

**Comment by Hunanbean** [comment]
The reason for the report is that "Using ctrl + alt + z to get out of super focus mode opens side bars that had been collapsed" meaning, it is not the state that it went in to focus mode with. It has uncollapsed a side bar that was manually collapsed.

**Comment by ryanpcmcquen** [comment]
I cannot reproduce that behavior. Do you have other plugins enabled?

**Comment by Hunanbean** [comment]
Tested with no 3rd party plugins. Problem persists.
For a test, you can drag the graph view into the right side panel to create
a valid window there. Collapse the right side panel using the arrow
provided.

KB shortcut to SFM, keyboard shortcut ctrl+alt+z notice the right side
panel is open now, when you left it closed before entering SFM

**Comment by pbienst** [comment]
I can confirm this bug: entering superfocus mode through keyboard shortcut, then exiting it by clicking the icon in the left ribbon, opens the tag panel even though it was closed before.

Perhaps this bug report should be reopened?

**Comment by ryanpcmcquen** [comment]
> I can confirm this bug: entering superfocus mode through keyboard shortcut, then exiting it by clicking the icon in the left ribbon, opens the tag panel even though it was closed before.
> 
> Perhaps this bug report should be reopened?

What plugins are you runnning?

**Comment by pbienst** [comment]
The problem occurs even when no other plugins are running.

**Comment by ryanpcmcquen** [comment]
> The problem occurs even when no other plugins are running.

Can you record a video?

**Comment by pbienst** [comment]
There you go: https://www.dropbox.com/s/afdq7ga1s7nmuz0/2022-05-06%2020-59-02.mkv?dl=0

**Comment by ryanpcmcquen** [comment]
> There you go: https://www.dropbox.com/s/afdq7ga1s7nmuz0/2022-05-06%2020-59-02.mkv?dl=0

Is this a custom theme? I still can't reproduce.

**Comment by pbienst** [comment]
Changing to the default theme does not help...

**Comment by ryanpcmcquen** [comment]
> Changing to the default theme does not help...

I'll try to do some more testing this weekend.

**Comment by ryanpcmcquen** [comment]
I reproduced this today, working on a fix!

**Comment by ryanpcmcquen** [comment]
Fixed!
https://github.com/ryanpcmcquen/obsidian-focus-mode/releases/tag/1.8.3

**Comment by pbienst** [comment]
Works indeed! Thanks a lot!
