### ISSUE TITLE
[BUG] Focus mode open collapse ribbon

### ISSUE THREAD

**Issue by Mara-Li** [ryanpcmcquen/obsidian-focus-mode#3]
When I have the right or/and left ribbon collapsed, the plugin will open it in blank, with no value. 
I need to open the ribbon to use the plugin without this bug.

**Comment by ryanpcmcquen** [comment]
Could you send a screenshot or recording of what you are seeing?

**Comment by ryanpcmcquen** [comment]
As far as I can tell, there are 4 possible states, all of which work as I would expect here.

1. No ribbons expanded:
![no_ribbons_focus](https://user-images.githubusercontent.com/772937/118010834-3e378880-b304-11eb-8f6f-dc71fda8aa90.gif)
2. Left ribbon only expanded:
![left_ribbon_only_focus](https://user-images.githubusercontent.com/772937/118010875-45f72d00-b304-11eb-8350-f6020568da73.gif)
3. Right ribbon only expanded:
![right_ribbon_only_focus](https://user-images.githubusercontent.com/772937/118010904-4d1e3b00-b304-11eb-9a88-e3519638a4f6.gif)
4. Both left and right ribbon expanded:
![left_and_right_ribbon_focus](https://user-images.githubusercontent.com/772937/118010955-57d8d000-b304-11eb-8fdd-100af39e2467.gif)

**Comment by Mara-Li** [comment]
Hello, here is the gif !

![05-12-2021_23-25](https://user-images.githubusercontent.com/30244939/118051653-a5dfe900-b381-11eb-9de9-25c19e0e312d.gif)

**Comment by ryanpcmcquen** [comment]
What other plugins do you have installed?

**Comment by Mara-Li** [comment]
- Underline
- Todist Plugin
- Text Expander
- Templater
- Tag Wrangler
- Table of Contents
- Table extended
- Supercharged Links
- Spaced Repetition
- Snippets Plugin
- Show the current open note in the window title
- Search++
- Review
- Remember cursor position
- Recent files
- Recall
- Prettier Format
- PDF to markdown
- Pandoc plugin
- Ozan's Image in Editor Plugin
- Outliner
- Obsidian TODO | Text-based GTD
- Obisidan Leaflet
- Obsidian Charts
- Natural Language Dates
- Mind Map
- Media Extended
- Markdown prettifier
- Markdown formatting assistant
- Latex environment
- Kanban
- Language Tool Integration
- Icons
- Icon Swapper
- Hotkey for templates
- Hider
- Footnote shortuct
- Folder note
- Focus Mode (obviously)
- Excalidraw
- Editor Syntax Highlight
- Discord Rich Presence
- Day Planner
- Dataview
- CSV editor
- Copy Button
- Convert URL to preview
- Contextual Typography
- Completed Area
- Clear Unused Image
- Citations
- Checklist
- Calendar
- Better word count
- Better PDF 
- Advanced Tables
- Admonition

**Comment by ryanpcmcquen** [comment]
Wow! That is quite the list. It's almost certainly the result of one of those plugins having a pane that closes in a 'non-standard' way. Although I'd love to be able to support every permutation of plugin installs, I hope you can understand why that would be nearly impossible. This isn't really a bug, so much as a result of having this many plugins which interact with the DOM in a myriad of ways.

If you have the time/knowledge to open the dev tools and debug your own setup, and find a way to close all those panes programmatically, I wouldn't mind incorporating a fix you find, but honestly I wouldn't even have time to duplicate and debug the install setup you currently have.

If you aren't comfortable with the dev tools, you could also disable your plugins one by one to see which is the issue (I'd start with that Calendar one). I would say this is actually the bug of another plugin modifying the DOM in a strange way, if we found that, I can help you write the bug report for that 'other' plugin.

**Comment by Mara-Li** [comment]
Yeah, no worry for that ! I give you all the list to know if you have already an idea :)
I will check plugin one by one and send you the bad plugin, in case of future bug report :). I will check too my snippet... In case of :).

Thanks you !

**Comment by ryanpcmcquen** [comment]
Wait ... you can repro this with a completely blank vault? With no other plugins? What platform is that on. What version of Obsidian?

**Comment by ryanpcmcquen** [comment]
@Mara-Li, could you try version 1.2.2 that I just pushed up. I am attempting a different method for collapsing/closing stuff. Hoping it will resolve your issue!

**Comment by Mara-Li** [comment]
Your new version work perfectly! Thank you :D
