### ISSUE TITLE
[Feature Request] A toggle between normal mode and supper focus mode

### ISSUE THREAD

**Issue by Archie-2021** [ryanpcmcquen/obsidian-focus-mode#31]
Adding a command and hotkey to toggle between normal mode and supper focus mode. Right now when one enters super focus mode and want to get out of it he has to first go back to focus mode and then out of there to normal mode.

**Comment by Archie-2021** [comment]
> 'Toggle Focus Mode' does this.

**Comment by pbienst** [comment]
That still requires you to have two keypresses. It would be nice if "Toggle Super Focus Mode" only switched between normal mode and super focus mode...

**Comment by ryanpcmcquen** [comment]
> That still requires you to have two keypresses. It would be nice if "Toggle Super Focus Mode" only switched between normal mode and super focus mode...

That's what it does.

**Comment by ryanpcmcquen** [comment]
> That still requires you to have two keypresses. It would be nice if "Toggle Super Focus Mode" only switched between normal mode and super focus mode...

To clarify:

- Obsidian starts in 'normal mode'.
- "Toggle Super Focus Mode" activates 'Super Focus'.
- "Toggle Focus Mode" switches back to 'normal mode'. One command per action. I would not define this as two keypresses.

**Comment by pbienst** [comment]
OK, I see. In that case, the 'toggle' in "Toggle Super Focus Mode" is a bit misleading, since I'd expect that the same key press takes you into and back out of super focus mode. I still believe it would be more convenient and easier to understand if that was the actual behaviour...

**Comment by ryanpcmcquen** [comment]
> OK, I see. In that case, the 'toggle' in "Toggle Super Focus Mode" is a bit misleading, since I'd expect that the same key press takes you into and back out of super focus mode. I still believe it would be more convenient and easier to understand if that was the actual behaviour...

But then there would be no direct path from 'Super Focus' to 'Focus' mode, and we'd end up with a ticket requesting that route with one keypress.

**Comment by ryanpcmcquen** [comment]
> OK, I see. In that case, the 'toggle' in "Toggle Super Focus Mode" is a bit misleading, since I'd expect that the same key press takes you into and back out of super focus mode. I still believe it would be more convenient and easier to understand if that was the actual behaviour...

And expanding on this, it does toggle Super Focus Mode, it just toggles it back to Focus Mode instead of Normal Mode.

**Comment by tonyxiao** [comment]
I think toggle is a very misleading word to use. Whenever you toggle something, you expect toggling it again will get you back to where you started. Perhaps the command should be called something different?

**Comment by ryanpcmcquen** [comment]
It toggles the state of Super Focus Mode, which exists as a subset of Focus Mode.

If you have a suggestion for more explicit wording let me know.

**Comment by maxwellhibbert** [comment]
> It toggles the state of Super Focus Mode, which exists as a subset of Focus Mode.

If it's called 'toggle' and it can go straight into super mode without being in normal focus first, then it should be able to come straight out as well, yeah?

> But then there would be no direct path from 'Super Focus' to 'Focus' mode, and we'd end up with a ticket requesting that route with one keypress.

Maybe two hotkeys would make everyone happy?  :)

**Comment by ryanpcmcquen** [comment]
There is already a hotkey for any state to any other state.

**Comment by maxwellhibbert** [comment]
> There is already a hotkey for any state to any other state.

Except from super focus back to normal. Multiple hotkeys are required to do that, which is annoying to use if you're not interested in the regular Focus mode.

What I was suggesting was another hotkey could be added to actually toggle between normal mode and super, while keeping the hotkeys you already have the same.

**Comment by ryanpcmcquen** [comment]
> > There is already a hotkey for any state to any other state.
> 
> Except from super focus back to normal. Multiple hotkeys are required to do that, which is annoying to use if you're not interested in the regular Focus mode.
> 
> What I was suggesting was another hotkey could be added to actually toggle between normal mode and super, while keeping the hotkeys you already have the same.

'Toggle Super Focus Mode' hotkey enables 'Super Focus Mode'. Then the 'Toggle Focus Mode' hotkey takes you back to normal mode. Only one interaction for each status change.

**Comment by maxwellhibbert** [comment]
> Only one interaction for each status change.

Two separate hotkeys though, that's the issue.

**Comment by ryanpcmcquen** [comment]
> > Only one interaction for each status change.
> 
> Two separate hotkeys though, that's the issue.

Are you rapidly switching between Super Focus and normal modes?

**Comment by maxwellhibbert** [comment]
Super Focus is the only focus I use, which is why I want to just toggle that on and off with a single hotkey.

**Comment by ryanpcmcquen** [comment]
> Super Focus is the only focus I use, which is why I want to just toggle that on and off with a single hotkey.

I understand but there isn't a huge benefit to adding code/complexity to the plugin for this purpose. I am confident you could get used to one hotkey for activating Super Focus and another for disabling it.

**Comment by esaHD** [comment]
If that's the case, then this isn't functioning as a toggle—it doesn't switch states.
I don’t mean to sound harsh, but I believe this issue needs to be addressed or by renaming the functionaly or by actually implment it.

**Comment by ryanpcmcquen** [comment]
As said before:
https://github.com/ryanpcmcquen/obsidian-focus-mode/issues/31#issuecomment-1319195943
