### ISSUE TITLE
[Feature Request] show/hide page name option

### ISSUE THREAD

**Issue by woshitoutouge** [ryanpcmcquen/obsidian-focus-mode#32]
I love this plugin, but when open 2 or more pages, I can't see page name, and it takes 2 keyboard shortcut to  i use  hide left and right sidebar.
could you add this page name option, so we can chose show page name or not
![image](https://user-images.githubusercontent.com/99337435/173560733-169374b0-198b-4d8d-96e8-3f861495852f.png)

**Comment by ryanpcmcquen** [comment]
Why does it take two keyboard shortcuts? One should be able to get you to either state.

**Comment by woshitoutouge** [comment]
I didn't make myself clear.
page name is important to me, i want to see it when toggle on focus mode, that's what i ask for
For a similiar effect (without the plugin) is to use obsidian hotkeys, but i have to set 2 hotkeys to hide left sidebar and right sidebar
![image](https://user-images.githubusercontent.com/99337435/173608154-371e7fda-f96f-440f-90cb-e645e64bab05.png)

**Comment by woshitoutouge** [comment]
> Gotcha, what's the CSS selector you are trying to show? I can merge a PR that adds it, but don't have time to do it right now.

I have no clue what you are saying😀 just want show page name when toggle on focus mode.
And it's just a request, whenever you want to do it, it's ok

![image](https://user-images.githubusercontent.com/99337435/173621300-89afdbea-9246-46f0-bc36-83aaddf5d182.png)

**Comment by ryanpcmcquen** [comment]
I like the idea, I just don't have time to implement it now. Hoping someone else can contribute.

**Comment by woshitoutouge** [comment]
Now I understand, I mean whenever you have time to update, totally fine to me. Take your time and thanks for your reply.

**Comment by ryanpcmcquen** [comment]
@woshitoutouge how does this look?
![focus_mode_demo_with_page_title](https://user-images.githubusercontent.com/772937/174421818-27449d91-486b-4b8d-aa1c-1be9259707b4.gif)

**Comment by woshitoutouge** [comment]
@ryanpcmcquen That's great, it works perfectly! Thanks a lot
