### ISSUE TITLE
Focus is lost during selection

### ISSUE THREAD

**Issue by zoxal** [ryanpcmcquen/obsidian-focus-mode#33]
Hello. 
Thanks a lot for you plugin, I appreciate your work.
I found than when I select a word (I'm doing it all the time during writing), focus is lost from the line. 

![obsidian-focus-is-lost2](https://user-images.githubusercontent.com/15104938/174992399-8d445a41-4d75-46c8-8692-d64f265e8208.gif)

It would be nice if you can fix it, thanks.

**Comment by zoxal** [comment]
Found the reason and solution.

**Reason**: `CodeMirror-activeline` class that you use to detect active line is removed during selection with default settings.
**Solution**: Override default setting to preserve `CodeMirror-activeline` class on selection, see [obsidian forum post](https://forum.obsidian.md/t/persist-codemirror-activeline-class-on-editor-text-selection/19969/7).

I installed [obsidian-codemirror-options](https://github.com/nothingislost/obsidian-codemirror-options) plugin and enabled option 'Retain active line on selection', now works fine.

You can close the ticket.

**Comment by ryanpcmcquen** [comment]
Interesting! Obsidian should enable that by default.
