### ISSUE TITLE
Obsidian V1.0 Introduces tabs.

### ISSUE THREAD

**Issue by generic-user** [ryanpcmcquen/obsidian-focus-mode#35]
Hi,
Obsidian V1.0 introduces tabs, those tabs and some other UI elements are not hidden.

**Comment by ryanpcmcquen** [comment]
Or maybe keep the tabs:
<img width="1612" alt="Screen Shot 2022-10-18 at 9 15 04 AM" src="https://user-images.githubusercontent.com/772937/196486082-a5d2db1a-4af9-4dee-ba94-328d0287faf8.png">

**Comment by ryanpcmcquen** [comment]
Let me know if you hit issues:
https://github.com/ryanpcmcquen/obsidian-focus-mode/releases/tag/1.10.0
