### ISSUE TITLE
Styling error on the left edge in Obsidian v1.0

### ISSUE THREAD

**Issue by tbenthompson** [ryanpcmcquen/obsidian-focus-mode#36]
The dark styling extends up into the three Mac window buttons. 

<img width="458" alt="image" src="https://user-images.githubusercontent.com/4241811/196577374-e7716015-60d9-4e6a-8ff5-6a30805b59a1.png">

When Focus Mode is off, the styling is correct: 

<img width="201" alt="image" src="https://user-images.githubusercontent.com/4241811/196577451-45429c31-667d-4239-8328-e93d58dd8634.png">

Thank you for this awesome extension!!

**Comment by ryanpcmcquen** [comment]
Thank you, I will get a fix out shortly.

**Comment by tbenthompson** [comment]
Awesome!! Thanks.

**Comment by ryanpcmcquen** [comment]
Try this:
https://github.com/ryanpcmcquen/obsidian-focus-mode/releases/tag/1.10.1

**Comment by tbenthompson** [comment]
Yep, all fixed. Nice!! Thanks again.
