### ISSUE TITLE
Super focus doesn't(?)  work in Obsidian 1.0.3

### ISSUE THREAD

**Issue by danieltomasz** [ryanpcmcquen/obsidian-focus-mode#38]
Superfocus make the pane that is not in focus blank, but doesn't hide it

<img width="1680" alt="Vault_is_just_a_local_folder_-_Obsidian_Sandbox_-_Obsidian_v1_0_3" src="https://user-images.githubusercontent.com/7980381/198400993-6d5accff-12be-4819-9cea-c1137b87c3b5.png">

**Comment by ryanpcmcquen** [comment]
Would accept a PR fixing this, it's a wee bit tricky.

**Comment by danieltomasz** [comment]
I dont know if this helps but full pane focus is able to get cure leaf  when in two pane view (although make it full screen instead of full window)
https://github.com/Razumihin/obsidian-fullscreen-plugin

**Comment by ryanpcmcquen** [comment]
Will you try the latest version and let me know if you have any issues?
https://github.com/ryanpcmcquen/obsidian-focus-mode/releases/tag/1.11.0

**Comment by danieltomasz** [comment]
Great, it works! Thank you for fixing this? The look into other plugin was useful?

Only thing I noticed is this
1. I have view with 2 panes open
<img width="977" alt="image" src="https://user-images.githubusercontent.com/7980381/198974062-6988875c-1c95-464d-99ee-049561c2e128.png">

When I superfocus on the right pane the tab  bar overlap with the windows buttons, this effect doesnt happen when I focus on the left pane
<img width="977" alt="image" src="https://user-images.githubusercontent.com/7980381/198974497-c03911dd-ec5f-4d72-aca9-61334590acb4.png">
<img width="977" alt="image" src="https://user-images.githubusercontent.com/7980381/198974590-addec07d-46e3-4e80-8178-1f25cf66c108.png">


Also unexpected behaiour when 
https://github.com/NomarCub/obsidian-hide-sidebars-on-window-resize
is active
1.Activate superfocus mode when the obsidian window is smaller (half of the screen)
4. Maximalize Obsidian Window
5. the Hide sibars plugin attempt to add sidebar

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/7980381/198976553-b7b9cf0d-f561-4208-811e-6523008429d5.png">

Dont expect this to be fixed, but maybe info in the readme will be useful

**Comment by ryanpcmcquen** [comment]
I'll look into a fix for the window button overlap. I don't use that other plugin so I'm not sure what it is doing.

**Comment by ryanpcmcquen** [comment]
@danieltomasz attempted to fix the window button overlap, let me know what you think:
https://github.com/ryanpcmcquen/obsidian-focus-mode/releases/tag/1.11.1

**Comment by danieltomasz** [comment]
yes, this works fine!
