### ISSUE TITLE
Super focus mode does not restore open state of sidebars

### ISSUE THREAD

**Issue by ronrdev** [ryanpcmcquen/obsidian-focus-mode#40]
Unless I'm missing a click pattern to do this, I noticed is that focus mode closes and opens sidebars, but when entering super focus mode with sidebars open, the plugin does not reopen them when toggling back. Talking about the default left and right side bars Obsidian provides.

Attached a new video showing super focus mode closing sidebars but they never open back up (tried shift clicks and clicks) until I manually opened with button to demonstrate regular focus mode working as expected with side bars toggling closed and open.

https://user-images.githubusercontent.com/13022919/199405875-0582a09a-993a-499c-9b73-cd2fe9a1fb67.mp4

**Comment by ryanpcmcquen** [comment]
This should be fixed in the latest release (1.11.4).

**Comment by ronrdev** [comment]
Tested the new release. Can confirm it's working for me as expected behavior, up to date with Obsidian's big V1. I guess Obsidian is going to be stable for while so these workflows are good to go.
Thanks

**Comment by ryanpcmcquen** [comment]
@ronrdev, thank you!
