### ISSUE TITLE
Super focus mode stacked tabs compatibility for hiding vertical tabs

### ISSUE THREAD

**Issue by ronrdev** [ryanpcmcquen/obsidian-focus-mode#41]
Might be low priority. 

I don't use stacked tabs/sliding panes but I tested it and the vertical tabs are still visible in super focus mode and clickable to pull focus on other notes. Everything else is hidden.

When toggling into and out of focus mode and super focus mode with stacked tabs in use there is unexpected behavior. Vertical tabs and other notes are hidden, then are visible, multiple clicks seem to hide them, may hide or reveal other panels. Attached video. 

https://user-images.githubusercontent.com/13022919/199408760-19edde6f-cf81-483b-9316-2d39d7c4a18e.mp4

**Comment by danieltomasz** [comment]
I dont know if this is intended but for me as an occasional user of staked tabs this  behaviour is useful
SuperFocus allow me to focus on the pane, even if there is more stacked tab,
Normal Focus work in similar way for stacked tabs, only difference is that Focus doesnt hide the second pane

**Comment by ryanpcmcquen** [comment]
I don't mind the current behavior, you still have one maximised note, but you can switch between tabs in that pane. I see this as more of a feature than a bug.

**Comment by ryanpcmcquen** [comment]
You can further modify the behavior of Super Focus Mode with the `.super-focus-mode` class if desired:

https://github.com/ryanpcmcquen/obsidian-focus-mode#customizing-the-plugins-appearance
