### ISSUE TITLE
superfocus mode does not toggle back to normal mode

### ISSUE THREAD

**Issue by tonyxiao** [ryanpcmcquen/obsidian-focus-mode#42]
When I toggle from normal to super focus mode, then try to toggle back again, it remains in focus mode, and I have to separately disable to focus mode in order to return to normal mode. It seems that it should remember the previous state when toggling such that it returns to the right state.

**Comment by ryanpcmcquen** [comment]
Same question as here:
https://github.com/ryanpcmcquen/obsidian-focus-mode/issues/31#issuecomment-1115077073

The current functionality allows a direct path between all states with one interaction.
