### ISSUE TITLE
Blank outline in super Focus Mode

### ISSUE THREAD

**Issue by TrustTepee** [ryanpcmcquen/obsidian-focus-mode#43]
HI there.  Love the plugin. I am encountering an issue however. I have hotkeys set up to toggle both side panes individually.  When I activate super focus mode but then try to toggle one or the other side pane, it shows up, but it shows up entirely empty. 
I do not have this issue in the regular focus mode which I do not use much. 

This is inconvenient because I often refer to the outline of a note when working,  so if I want to focus on a single note, I no longer have access to the outline without having to come in and out of super focus mode every time I want to see the outline or jump around in the note through the outline. So having access to the outline would really be useful. 

I've attached an image for reference. 

Is there any possible fix to this issue? Thank you!

<img width="2035" alt="Screen Shot 2022-11-17 at 12 34 58 PM" src="https://user-images.githubusercontent.com/116844193/202519100-da8b6d09-235a-45fb-9c63-6780638fef70.png">

**Comment by ryanpcmcquen** [comment]
Is there a reason you cannot use Focus Mode instead. Super Focus Mode is meant to hide everything but the note.

**Comment by TrustTepee** [comment]
I understand,  but I would like to be able to make use of super focus mode, which neatly focuses a single note, centers it etc., while still having the ability to summon the side panes using the built in toggle right/left side pane common? (I made great use of the outline on a day to day basis but I can also imagine needing to quickly access other things).  Since I used a hotkey to display and hide the side panes, I can quickly hide them back once done. 

A great thing about Obsidian is how customizable it is.  Seeing as the panes do come back in view when summoned (although empty), could there be a way to have them hidden when focus mode is activated (as is the case right now) but to not be empty when summoned ?  In the CSS perhaps? Or a CSS snippet? I'm not the most knowledgeable on this front. Any help would be much appreciated. Love the plugin.

**Comment by TrustTepee** [comment]
Someone just informed me that [ this plugin](https://github.com/pjeby/pane-relief/blob/0.3.3/README.md) does something similar to what I am describing. I

**Comment by ryanpcmcquen** [comment]
Yes, a CSS snippet could easily solve this, which Obsidian supports out of the box. Willing to accept a PR on this.

**Comment by ryanpcmcquen** [comment]
Will reopen if someone wants to solve this.
