### ISSUE TITLE
Do you know how to add a settings menu?

### ISSUE THREAD

**Issue by mwufi** [ryanpcmcquen/obsidian-focus-mode#46]
I changed mine to display the status bar
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/30219253/211170274-dbae09dc-c6d0-4364-aa08-726506520f10.png">

But... maybe I can figure out how to add it to settings! So that the user can toggle some settings
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/30219253/211170284-7c77fb12-ec76-4841-a157-acc410743c13.png">

**Comment by ryanpcmcquen** [comment]
No thank you, I prefer no settings as they are distracting.
