### ISSUE TITLE
When entering Super FOCU mode, the right sidebar content is not displayed

### ISSUE THREAD

**Issue by Kiss-World** [ryanpcmcquen/obsidian-focus-mode#50]
I hope to be the same as the normal FOCU mode, because sometimes it will be full screen, and some information display on the right sidebar is controlled by shortcut keys.
win11_v1.4

**Comment by ryanpcmcquen** [comment]
Super Focus Mode should be hiding the right sidebar. If you want to change the behavior see here:
https://github.com/ryanpcmcquen/obsidian-focus-mode#customizing-the-plugins-appearance
