### ISSUE TITLE
How do I hide all interface elements, including tabs, like in the demo animations?

### ISSUE THREAD

**Issue by rustbuckett** [ryanpcmcquen/obsidian-focus-mode#55]
This isn't really an issue with the plugin, per se, but there isn't a Discussion tab in this repo.

I'd like to have focus-mode or super-focus-mode hide all elements of the obsidian interface, including the tabs. The demo animations imply that this is possible, but I don't see how to do it.

**Comment by ryanpcmcquen** [comment]
The interface has changed quite a bit over the years, but you can add additional CSS as referenced here:
https://github.com/ryanpcmcquen/obsidian-focus-mode?tab=readme-ov-file#customizing-the-plugins-appearance
