### ISSUE TITLE
Tab section of window is not removed

### ISSUE THREAD

**Issue by reidempey** [ryanpcmcquen/obsidian-focus-mode#56]
Maybe I just haven't configured it correctly, but when I enable Focus Mode, the tab banner is still visible at the top.  
![image](https://github.com/user-attachments/assets/244ab941-8aeb-4aa3-aacd-19d91ce4c92e)

I'm on Windows 10, Focus Mode v. 1.11.5, Obsidian v. 1.7.5.

**Comment by ryanpcmcquen** [comment]
This is expected, but configurable with CSS snippets, see here for details:
https://github.com/ryanpcmcquen/obsidian-focus-mode?tab=readme-ov-file#customizing-the-plugins-appearance
