### ISSUE TITLE
Slow file deletion when in focus mode

### ISSUE THREAD

**Issue by HynDuf** [ryanpcmcquen/obsidian-focus-mode#57]
A noticeable delay around 4-6 seconds when delete a file in focus mode

**Comment by ryanpcmcquen** [comment]
I just tested this on desktop and the deletion time with Focus Mode on or off was the same. Can you provide some more details about your setup and the kind of files you are deleting with Focus Mode enabled/disabled?

**Comment by HynDuf** [comment]
Oh I tested more carefully and the real culprit was the Tasks plugin. But somehow when in Focus mode it exaggerated the issue. Probably something related to Tasks recalculate the cache or sth when delete a file. Sorry and thanks for your time though.

**Comment by ryanpcmcquen** [comment]
@HynDuf thank you!
