### ISSUE TITLE
Remember/restore ribbon state?

### ISSUE THREAD

**Issue by ryanpcmcquen** [ryanpcmcquen/obsidian-focus-mode#9]
It might be nice to store the left and right ribbon states when activating 'Focus Mode', so that we could restore those when disabling 'Focus Mode'.

**Comment by emrergin** [comment]
I definitely support this, since it already exists in https://github.com/razumihin/obsidian-fullscreen-plugin.

**Comment by apotenza92** [comment]
I was literally about to post this exact request as well. Just makes sense to maintain state.

**Comment by ryanpcmcquen** [comment]
> I definitely support this, since it already exists in https://github.com/razumihin/obsidian-fullscreen-plugin.

It is a bit different for that plugin. Since it only supports the active pane, which is analogous to 'Super Focus Mode' here. We actually have to store state within memory for this. But it really isn't too tricky.

**Comment by ryanpcmcquen** [comment]
Landed in 1.5.0!
